export const myGarageInitialState = {
  isVisibleZoneModal: false,
  loading: false,
  zones: [],
  filterData: '',
  currentZone: null,
  driversList: [],
  vehiclesList: [],
  driverForEdit: null,
  ratesList: [],
  vehicleForEdit: null,
  addDriverModal: false,
  editDriverModal: false,
  addCarModal: false,
  editVehicleModal: false,
  frontPageAddVehicleModal: false,
  sendToDriverInviteToAppModal: false,
  resetDriverPasswordModal: false,
};
